### ISSUE TITLE
[FIXED] Using JAVA SDK > 8 crashes on start.

### ISSUE THREAD

**Issue by livingfaraway** [DxxxxY/Hephaestus#6]
Exception in thread "main" java.lang.IllegalAccessError: superclass access check failed: class studio.dreamys.Tasks$1 (in unnamed module @0x4f3f5b24) cannot access class jdk.internal.org.objectweb.asm.commons.Remapper (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm.commons to unnamed module @0x4f3f5b24
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at studio.dreamys.Hephaestus.main(Hephaestus.java:35)

**Comment by DxxxxY** [comment]
Use Java 8.
